# Generated by Django 3.1.1 on 2020-11-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('img_path', models.CharField(max_length=150)),
            ],
        ),
    ]
