# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      BUILD_SH: "
                PROJ_DIR=$$HOME/shop/;
                BUILD_DIR=$$PROJ_DIR/build/;
                rm -rf $$BUILD_DIR;
                mkdir $$BUILD_DIR && cd $$BUILD_DIR;
                git clone https://$USERNAME:$PASSWORD@${{ github.repository }} $$BUILD_DIR;
                "
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: add fingerpring
        run: |
          touch ~/.ssh/authorized_keys
          touch ~/.ssh/private
          echo $TOKEN > ~/.ssh/authorized_keys
          echo $TOKEN > ~/.ssh/private
          sudo chmod 600 ~/.ssh/authorized_keys
          sudo chmod 600 ~/.ssh/private

      - name: run ssh
        run: ssh -i ~/.ssh/private -o "StrictHostKeyChecking=no"  -T Maria@54.85.9.45 "bash -c '$BUILD_SH'"
